config/routes.rb
Rails.application.routes.draw do
  root "jobs#index"
  resources :jobs
  resources :users, only: :create do
    collection do
      post 'confirm'
      post 'login'
    end
  end
  resources :sessions, only: [:update]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    
    user ||= User.new
    if user.role?(:admin)
      can :manage, :all
    elsif user.role?(:user)
      can :read, Job
      #can :create, Job
      #can :update, Job
    end

 #can :manage, Project
#cannot :destroy, Project
    # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/jobs_user.rb
class JobsUser < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :email
  validates_uniqueness_of :email, case_sensitive: false
  validates_format_of :email, with: /@/
  has_secure_password
  before_save :downcase_email
  before_create :generate_confirmation_instructions
  def downcase_email
    self.email = self.email.delete(' ').downcase
  end
  
  def generate_confirmation_instructions
    self.confirmation_token = SecureRandom.hex(10)
    self.confirmation_sent_at = Time.now.utc
  end

  ROLES = {0 => :user, 1 => :admin}

  attr_reader :role

  def initialize(role_id = 0)
    @role = ROLES.has_key?(role_id.to_i) ? ROLES[role_id.to_i] : ROLES[0]
  end

  def role?(role_name)
    role == role_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CanCan::ControllerAdditions
  require 'json_web_token'
  protect_from_forgery with: :exception

  protected
  # Validates the token and user and sets the @current_user scope
    def authenticate_request!
      if !payload || !JsonWebToken.valid_payload(payload.first)
        return invalid_authentication
      end

  load_current_user!
  invalid_authentication unless @current_user
  end

  # Returns 401 response. To handle malformed / invalid requests.
  def invalid_authentication
    render json: {error: 'Invalid Request'}, status: :unauthorized
  end

  private
  # Deconstructs the Authorization header and decodes the JWT token.
  def payload
    auth_header = request.headers['Authorization']
    token = auth_header.split(' ').last
    JsonWebToken.decode(token)
  rescue
    nil
  end

  # Sets the @current_user with the user_id from payload
  def load_current_user!
    @current_user = User.find_by(id: payload[0]['user_id'])
  end
  private

  def current_user
    User.new(session[:id])
  end

  helper_method :current_user

  rescue_from CanCan::AccessDenied do |exception|
    root_path ="/"
    flash[:warning] = exception.message
    redirect_to root_path
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /jobs
  # GET /jobs.json
  
  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  

  # GET /jobs/1/edit
  

  # POST /jobs
  # POST /jobs.json
  def create
    if @job.save
      flash[:success] = 'job was saved!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    if @job.update_attributes(job_params)
      flash[:success] = 'job was updated!'
      redirect_to root_path
    else
      render 'edit'
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    if @job.destroy
      flash[:success] = 'job was destroyed!'
    else
      flash[:warning] = 'job destroy this job...'
    end
    redirect_to root_path
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:company_name, :position, :status, :job_detals)
    end
end

app/controllers/jobs_users_controller.rb
class JobsUsersController < ApplicationController
  before_action :set_jobs_user, only: [:show, :edit, :update, :destroy]

  # GET /jobs_users
  # GET /jobs_users.json
  def index
    @jobs_users = JobsUser.all
  end

  # GET /jobs_users/1
  # GET /jobs_users/1.json
  def show
  end

  # GET /jobs_users/new
  def new
    @jobs_user = JobsUser.new
  end

  # GET /jobs_users/1/edit
  def edit
  end

  # POST /jobs_users
  # POST /jobs_users.json
  def create
    @jobs_user = JobsUser.new(jobs_user_params)

    respond_to do |format|
      if @jobs_user.save
        format.html { redirect_to @jobs_user, notice: 'Jobs user was successfully created.' }
        format.json { render :show, status: :created, location: @jobs_user }
      else
        format.html { render :new }
        format.json { render json: @jobs_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs_users/1
  # PATCH/PUT /jobs_users/1.json
  def update
    respond_to do |format|
      if @jobs_user.update(jobs_user_params)
        format.html { redirect_to @jobs_user, notice: 'Jobs user was successfully updated.' }
        format.json { render :show, status: :ok, location: @jobs_user }
      else
        format.html { render :edit }
        format.json { render json: @jobs_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs_users/1
  # DELETE /jobs_users/1.json
  def destroy
    @jobs_user.destroy
    respond_to do |format|
      format.html { redirect_to jobs_users_url, notice: 'Jobs user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jobs_user
      @jobs_user = JobsUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jobs_user_params
      params.require(:jobs_user).permit(:company_name, :position, :status, :job_detals)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def update
      id = params[:id].to_i
      session[:id] = User::ROLES.has_key?(id) ? id : 0
      flash[:success] = "Your new role #{User::ROLES[id]} was set!"
      redirect_to root_path
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def login
        user = User.find_by(email: params[:email].to_s.downcase)
        
        if user && user.authenticate(params[:password])
            auth_token = JsonWebToken.encode({user_id: user.id})
            render json: {auth_token: auth_token}, status: :ok
        else
            render json: {error: 'Invalid username / password'}, status: :unauthorized
        end
    end

    def create
        user = User.new(user_params)
      
        if user.save
          render json: {status: 'User created successfully'}, status: :created
        else
          render json: { errors: user.errors.full_messages }, status: :bad_request
        end
      end
      
      private
      
      def user_params
        params.permit(:email, :password, :password_confirmation)
      end
      
      skip_before_action :verify_authenticity_token
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/jobs_users_helper.rb
module JobsUsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_area :company_name, id: :job_company_name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_area :position, id: :job_position %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_area :status, id: :job_status %>
  </div>

  <div class="field">
    <%= form.label :job_detals %>
    <%= form.text_area :job_detals, id: :job_job_detals %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
    <th>id</th>
      <th>Company name</th>
      <th>Position</th>
      <th>Status</th>
      <th>Job detals</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.id %></td>
        <td><%= job.company_name %></td>
        <td><%= job.position %></td>
        <td><%= job.status %></td>
        <td><%= job.job_detals %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @job.company_name %> <%= content_tag(:button, " Apply ", :type=>:submit)%>
</p>

<p>
  <strong>Position:</strong>
  <%= @job.position %>
</p>

<p>
  <strong>Status:</strong>
  <%= @job.status %>
</p>

<p>
  <strong>Job detals:</strong>
  <%= @job.job_detals %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs_users/_form.html.erb
<%= form_with(model: jobs_user, local: true) do |form| %>
  <% if jobs_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jobs_user.errors.count, "error") %> prohibited this jobs_user from being saved:</h2>

      <ul>
      <% jobs_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_area :company_name, id: :jobs_user_company_name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_area :position, id: :jobs_user_position %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_area :status, id: :jobs_user_status %>
  </div>

  <div class="field">
    <%= form.label :job_detals %>
    <%= form.text_area :job_detals, id: :jobs_user_job_detals %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs_users/edit.html.erb
<h1>Editing Jobs User</h1>

<%= render 'form', jobs_user: @jobs_user %>

<%= link_to 'Show', @jobs_user %> |
<%= link_to 'Back', jobs_users_path %>

app/views/jobs_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs Users</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Position</th>
      <th>Status</th>
      <th>Job detals</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs_users.each do |jobs_user| %>
      <tr>
        <td><%= jobs_user.company_name %></td>
        <td><%= jobs_user.position %></td>
        <td><%= jobs_user.status %></td>
        <td><%= jobs_user.job_detals %></td>
        <td><%= link_to 'Show', jobs_user %></td>
        <td><%= link_to 'Edit', edit_jobs_user_path(jobs_user) %></td>
        <td><%= link_to 'Destroy', jobs_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jobs User', new_jobs_user_path %>

app/views/jobs_users/new.html.erb
<h1>New Jobs User</h1>

<%= render 'form', jobs_user: @jobs_user %>

<%= link_to 'Back', jobs_users_path %>

app/views/jobs_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @jobs_user.company_name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @jobs_user.position %>
</p>

<p>
  <strong>Status:</strong>
  <%= @jobs_user.status %>
</p>

<p>
  <strong>Job detals:</strong>
  <%= @jobs_user.job_detals %>
</p>

<%= link_to 'Edit', edit_jobs_user_path(@jobs_user) %> |
<%= link_to 'Back', jobs_users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JopApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>